### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by jdecool** [omines/oauth2-gitlab#16]
The last tag is one year ago.

Some changes that remove deprecation with PHP 8.4 have not been released yet.

Could you create a new version ?

**Comment by curry684** [comment]
Hmmm interesting, I wouldn't expect that from the diffs: https://github.com/omines/oauth2-gitlab/compare/3.6.0...master

I'll need to add 8.4 to the test matrix anyway and add a new tag.

**Comment by curry684** [comment]
https://github.com/omines/oauth2-gitlab/releases/tag/3.7.0

**Comment by jdecool** [comment]
Thanks @curry684
