### ISSUE TITLE
Conflict with league/oauth2-client 2.4

### ISSUE THREAD

**Issue by codemonkey1988** [omines/oauth2-gitlab#6]
There is a new release of [league/oauth2-client](https://github.com/thephpleague/oauth2-client) that brings a breaking change for this package.

The method `League\OAuth2\Client\Provider\AbstractProvider::getResourceOwnerDetailsUrl` was updated by changing its argument type from `League\OAuth2\Client\Token\AccessToken` to `League\OAuth2\Client\Token\AccessTokenInterface`.
This breaks the class inheritance for `Omines\OAuth2\Client\Provider\GitLab::getResourceOwnerDetailsUrl`

**Comment by codemonkey1988** [comment]
There is a new release of league/oauth2-client package (2.4.1) that fixes this problem.
See https://github.com/thephpleague/oauth2-client/commit/bb12ba558b0e41b25aeb92e3ca989a8aa404c424#diff-58d25fe37b0dacc76bd6b7373506e480 

So there is only a conflict with version 2.4.0
Maybe a conflict entry in composer.json may be a good and easy solution here.

**Comment by curry684** [comment]
https://github.com/omines/oauth2-gitlab/releases/tag/3.1.2
